# Example - 1

- Displaying pipeline with Standard scaler and Estimator (Logistic regression)

In [ ]:
from sklearn.pipeline import Pipeline

# feature Scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [ ]:
steps = [("standard_scaler",StandardScaler()),
         ("classifier",LogisticRegression())]

In [ ]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [ ]:
pipe = Pipeline(steps)
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
# visualize the Pipeline

from sklearn import set_config

set_config(display = 'diagram')

pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
# creating a dataset

from sklearn.datasets import make_classification

X,y = make_classification(n_samples=1000)


In [ ]:
X.shape

(1000, 20)

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)


In [ ]:
X_train

array([[ 0.74404199, -0.45534111, -0.52950786, ..., -0.7041975 ,
         0.51279448, -1.3501395 ],
       [-1.23203963, -0.80650656, -0.67859432, ..., -0.72286506,
         0.58954155, -0.14315368],
       [-0.38891204, -0.06714577, -0.18701614, ..., -0.97022412,
        -0.47724294,  0.64032681],
       ...,
       [-0.19795369, -0.1913783 , -0.41295608, ..., -0.1438062 ,
         0.35680824, -1.97905422],
       [-1.51852285,  1.29880329,  2.27236504, ...,  0.90766441,
        -0.57001812, -1.35486193],
       [ 0.31498394, -0.78283432, -1.08560723, ..., -2.0218172 ,
        -0.25255762,  0.91680032]])

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [ ]:
y_pred = pipe.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,

# Example - 2

- Displaying pipeline with Standard scaler and dimensionality reduction and then Estimator (Logistic regression)

In [ ]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC


In [ ]:
steps =[("scaling",StandardScaler()),
        ("PCA",PCA(n_components=3)),
        ("SVC",SVC())]
steps

[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)), ('SVC', SVC())]

In [ ]:
pipe2 = Pipeline(steps)
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [ ]:
# pipe2['scaling'].fit_transform(X_train)  # if want to apply only scaling then we can do .

In [ ]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [ ]:
pipe2.predict(X_test)

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,

#Complex examples of columns transformer  

In [ ]:
from sklearn.impute import SimpleImputer

# for numerical processing pipeline
from sklearn.pipeline import Pipeline
import numpy as np

# feature Scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

numeric_processor = Pipeline(
    steps = [("imputation_mean",SimpleImputer(strategy='mean')),
             ("scaler",StandardScaler())]
)
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
# categorical processing pipeline

from sklearn.preprocessing import OneHotEncoder

categorical_processor = Pipeline(
    steps = [("imputation_constant",SimpleImputer(fill_value = -1,strategy = "constant")),
             ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value=-1, strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

#  Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target variable

# Convert X into a pandas DataFrame
X_df = pd.DataFrame(X, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)


In [ ]:
# combining processing technique

from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    [("categorical",categorical_processor,['sepal_length', 'sepal_width']),
     ("numerical",numeric_processor, ['petal_length', 'petal_width'])]
)

In [ ]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value=-1,
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['sepal_length', 'sepal_width']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['petal_length', 'petal_width'])])

In [ ]:
from sklearn.pipeline import make_pipeline

In [ ]:
make_pipeline(preprocessor,LogisticRegression())

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value=-1,
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['sepal_length',
                                                   'sepal_width']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['petal_length',
                                                   'petal_width'])])),
                ('logisticregression', LogisticRegression())])

In [ ]:
# Define the logistic regression model
logistic_regression_model = LogisticRegression()

# Combine preprocessing steps with the model
full_pipeline = make_pipeline(preprocessor, logistic_regression_model)


In [ ]:
# Fit the pipeline to your data
full_pipeline.fit(X_train, y_train)

# Make predictions
predictions = full_pipeline.predict(X_test)  # Assuming you have a separate test dataset X_test

In [ ]:
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

# Calculate accuracy score
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.9333333333333333
